### ISSUE TITLE
Using --user flag causes issues since 16.5.1

### ISSUE THREAD

**Issue by cascornelissen** [satanTime/puppeteer-node#14]
We use this container for visual testing in combination with Storybook and we're seeing an issue since a few days where the entire starting of the container seems to fail.

* `satantime/puppeteer-node:16` does not work
* `satantime/puppeteer-node:16.15.1` does not work
* `satantime/puppeteer-node:16.15.0` does work

We pull the image, create the container, add a file, and finally start the container using something similar to the snippet below. 

```
docker pull satantime/puppeteer-node:16
docker create --name example --user "${DOCKER_USER}" --mount "type=bind,source=${PWD},destination=/app" --workdir "/app" --rm satantime/puppeteer-node:16 /bin/sh -c "/bin/sh /app/.jest/start.sh ${JEST_OPTIONS}"
docker cp ${NPMRC_FILE} example:/.npmrc
docker start --attach example
```

This references a `start.sh` which, among other things, runs `npm rebuild`. When I mentioned the container is not working I meant that this file is executed but nothing in it seems to do, or at least output anything.

Passing `DOCKER_USER` is needed for our Bamboo CI/CD setup and is generated using the command below, resulting in something like `501:20`.

```
DOCKER_USER := $(shell echo $$(id -u):$$(id -g)) 
```

Removing the `--user` flag fixes the issue locally but prevents our CI/CD setup from working correctly. Did something change between `16.5.0` and `16.5.1` that could cause this? I can't seem to locate any changelog and the history isn't helping either 😅

**Comment by satanTime** [comment]
Hi @cascornelissen, could you check how it behaves when you use the original `node@16.5.1` image? It's clear that puppeteer is going to fail, but interesting to check whether the container can be created and executed.

**Comment by cascornelissen** [comment]
Looks like the problem is indeed related to `node:16.15.1`, I get pretty much the same crash-y output with using that version but Storybook starts running without issues when using `node:16.15.0`.

This is not my area of expertise at all but it seems similar to https://github.com/nodejs/docker-node/issues/1734?

**Comment by satanTime** [comment]
Hi @cascornelissen, there was an update of `16.5.1` images, could you check whether it has fixed your issue?

**Comment by cascornelissen** [comment]
Just did some testing and the requirement our CI/CD pipeline had earlier with regards to file ownership was loosened up a bit so we apparently don't need the `--user` flag anymore. So for now, for us at least, we can use the latest version again but the original issue still exists.

**Comment by satanTime** [comment]
I changed your code a bit for testing, and on my mac, I was able to execute `npm install && npm rebuild` with a changed user:

```shell
docker pull satantime/puppeteer-node:16
cd ~/project/simple-node
DOCKER_USER=501:20 docker create --name example --user "${DOCKER_USER}" --mount "type=bind,source=${PWD},destination=/app" --workdir "/app" --rm satantime/puppeteer-node:16 /bin/sh -c "npm install && npm rebuild"
docker start --attach example
```

The output on `npm install`:

```txt

> postinstall
> husky install

husky - Git hooks installed

added 19 packages, changed 1 package, and audited 2064 packages in 6s

259 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (7 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 8.11.0 -> 8.13.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.13.2>
npm notice Run `npm install -g npm@8.13.2` to update!
npm notice
```

The output on `npm rebuild`:

```txt
rebuilt dependencies successfully
```

Maybe, somehow permissions under `.npm` were messed up.

**Comment by cascornelissen** [comment]
Yeah, it's definitely a permission issue on the `.npm` directory. Again, I'm ok with closing this issue as this seems to be covered upstream by https://github.com/nodejs/docker-node/issues/1734. But I can also imagine it makes sense to keep it open here so others can find it faster, I'll leave that decision up to you ❤️

**Comment by satanTime** [comment]
Thanks for the update. I'm going to close the ticket, because it is still searchable.
